### PR TITLE
Japanese Edition of Solana Whitepaper v0.8.14

### PR DESCRIPTION
**Pull request by jangsa**
This is the Japanese edition of Solana whitepaper including catch-up with v0.8.14.
Automated PDF generation is not ready yet.

### CODE REVIEW

**Comment by ericlwilliams** [comment]
Thanks, Jang! I've sent a sample over to some friends for spot-checking (I don't speak Japanese) before a merge.  Will keep you posted.

**Comment by jangsa** [comment]
Thank you, Eric!
Several sentences are written based on free translation since scripts based on literal one sound very weird at some points.
If there are weird expressions that your friend spots, please feedback to me...Yes, anything!
That will help my further understandings about Solana. :)

**Comment by ericlwilliams** [comment]
@jangsa thanks for your hard work on this translation and your patience with the process!

**Comment by jangsa** [comment]
Happy to be merged!
Thank you for your great support. :)
Will take care of this work including coming Avalanche descriptions.

**Pull request merged**
